### PR TITLE
Expose DGESVD and DGESDD with all singular vector computation options.

### PR DESCRIPTION
**Pull request by millardjn**
Add two new constructors allowing choice of underlying algorithm,
and allowing full control over which singular vectors are computed.
Added methods for querying presence of right and left singular vectors independently.
U and Vt are no longer final to allow returning A when Overwrite job is used.

### CODE REVIEW

**Comment by fommil** [comment]
Great! Unfortunately (well, not really) I am on holiday so I cannot review this now. Please ping me in three weeks as a reminder.

**Comment by millardjn** [comment]
Hey,
Hope the holiday went well.
Just a ping as requested.

**Comment by fommil** [comment]
OK thanks! I'll try to take a look this weekend. I've got a lot to catch up on so just hassle me again if I'm slow on this.

**Comment by fommil** [comment]
sorry, I have a talk to prepare and haven't had time to look at this

**Comment by millardjn** [comment]
Hi,
Just chasing this again. Will you have a chance to review soon?

**Comment by fommil** [comment]
You're dead right, I had completely forgotten.

**Comment by fommil** [comment]
finally got to look at this. It seems like a useful feature, thank you.

But it feels like we are trying to shoehorn two different algorithms into the same class, do you think it might be cleaner if we just had different classes for each approach?

**Comment by millardjn** [comment]
It definitely a bit messy internally, particularly modifying internal matrix fields, which were final previously, and ternaries where the logic isn't immediately clear. Maintenance or future extensions will be a bit harder if left as is.

On the other hand, for the majority of users I think multiple classes could be unnecessary noise and source of confusion. For many applications SVD is SVD is SVD. It's only once you are running into stability or memory limits that you need to be aware of the different LAPACK algorithms, and multiple classes could push people to do unnecessary research before feeling comfortable making a choice.

I think it is a trade off that could go either way. I'm happy to try and make things clearer (starting with hasSingularVectors()!) or to refactor into a new class if you can sketch out what it should look like.

**Comment by fommil** [comment]
Have a think about it and see what you come up with. Worst case scenario, we fall back to this, but it would be nice to have something cleaner / simpler. I think I prefer having a separate class (with SVD in the name) as I trust users of this library to be competent at linear algebra and know how to start the class list for features.

**Comment by fommil** [comment]
ping

**Pull request closed without merging**
