### PR TITLE
Added the khatriRao operation to AbstractMatrix

### PR DESCRIPTION
**Pull request by roger62**
Additionally it was added a unit test to the operation.
The Khatri Rao operation description can be found in
https://en.wikipedia.org/wiki/Kronecker_product

### CODE REVIEW

**Comment by fommil** [comment]
I'll have a look at this when you fix the formatting changes thanks. There is a command you run to autoformat.

**Comment by roger62** [comment]
Thank you for the feedback.  Already formatted, also removed  a println in the unit test that was not supposed to go.

**Comment by fommil** [comment]
ok, cool thanks.

A few things:

1. this will be a rarely used feature, I'm wondering if perhaps it belongs as a utility class rather than something that lives on `Matrix`, e.g. similar to the `SVD` solver. What do you think?
2. can you please add a few more test cases, e.g. different row/column sizes.
3. out of interest, why did you find yourself needing this multiplication?

**Comment by roger62** [comment]
Yes, i don’t think it will be a frequently used operation, but i don’t think  it becomes as intuitive in a utility class, as it is a binary operation in matrices. Nonetheless, i added a commit with a Separate class for you to see if you are interested.   As far as i am aware there is no implementation in Blas/Lapack. 

It's one of the operations i had to experiment in my thesis, which seeks to experiment the [theory](http://link.springer.com/article/10.1007%2Fs00165-014-0316-9).

**Comment by fommil** [comment]
ok, cool! yes much cleaner as a separate class, but I think the target `C` should be a parameter to the `multiply` otherwise this can only be used once.

**Comment by fommil** [comment]
btw, the copyright is yours so please update the header :smile: no need for a longwinded license, it is in the LICENSE file.

**Comment by roger62** [comment]
Thank you for all the feedback :)  I have no experience with copyrights, i hope the header is fine this way.

**Comment by fommil** [comment]
Cool thanks, squash all the commits and I'll merge it.

Hint: git rebase interactively

**Comment by roger62** [comment]
Commits squashed.

**Comment by fommil** [comment]
if you could remove the public constructor of the test please, sorry i missed it before. no need to update the string interpolation, its just a comment. btw, have a look at lombok for boilerplate in general.

**Comment by roger62** [comment]
I've added the new version and already had a look at the lombok video. It seems nice, do you use it often ?

**Comment by fommil** [comment]
I can't look at Java without Lombok :-)

Thanks!

**Pull request merged**
