### PR TITLE
Added getRawData() method to be consistent with new getRawIndex() method

### PR DESCRIPTION
**Pull request by jbasilico**

### CODE REVIEW

**Comment by fommil** [comment]
cool thanks. I just realised that the changes could have been even more minimal... just use the Lombok annotations.

**Comment by fommil** [comment]
this actually failed when merged

```
Failed tests:   testUpperFactor(no.uib.cipr.matrix.SymmBandEigenvalueTest): expected:<0.9334548959685959> but was:<0.0>
```

but that might be an unrelated transient. I've never seen it before though.

**Comment by fommil** [comment]
@jbasilico I'm prepping a release 1.0.3 now. Should be out for you on Monday.

**Comment by jbasilico** [comment]
Thanks. I also think that test failure is a spurious one.

**Pull request merged**
